### PR TITLE
English short description changed and Russian translation of the short description added. Also fixed icon display

### PR DESCRIPTION
**Pull request by Artem13327**
https://github.com/SkyTubeTeam/SkyTube/pull/1135

### CODE REVIEW

**Comment by gzsombor** [comment]
Probably adding information what differentiates from the non-legacy version would be worthwhile - something like "which supports/supporting really old Android versions"

**Comment by gzsombor** [comment]
Yeah, sounds great!

**Comment by drogga** [comment]
@gzsombor, don't forget to remove the dead site from here too and also sync the other changes made to the other repo.

Here, at least the fastlane icon is in the proper place, unlike there... :D

**Comment by gzsombor** [comment]
Thanks for the patch!

**Comment by drogga** [comment]
I'm not seeing any E-Mail btw...

**Comment by gzsombor** [comment]
Sorry, rewriting the commit history is generally pain to everyone. 
And also, when I execute
`git log | grep Anonymous` 
I can see 'anonymous58630@gmail.com' 5 times, so it looks good to me.

**Pull request merged**
