### PR TITLE
Use StandardCharsets.

### PR DESCRIPTION
**Pull request by Isira-Seneviratne**
* Use the `desugar_jdk_libs_nio` artifact to desugar `StandardCharsets`.
* Use `StandardCharsets`.

### CODE REVIEW

**Comment by gzsombor** [comment]
Hi @Isira-Seneviratne , what do you think, when should we merge this?

**Comment by Isira-Seneviratne** [comment]
> Hi @Isira-Seneviratne , what do you think, when should we merge this? 

I was thinking when AGP 7.4.0 is released.

**Comment by Isira-Seneviratne** [comment]
@gzsombor I updated the PR.

**Comment by gzsombor** [comment]
So in the end, this will desugar StandardCharsets.ISO_8859_1 and StandardCharsets.UTF_8 references even in libraries? That will be nice. From my side, we can merge this.

**Comment by gzsombor** [comment]
Thanks for the patch! 
Btw, I think, you have the rights to merge pull requests...

**Comment by Isira-Seneviratne** [comment]
> Thanks for the patch! Btw, I think, you have the rights to merge pull requests...

My bad, I was a bit busy.

**Pull request merged**
